### PR TITLE
New Swim Speed Attribute

### PR DESCRIPTION
**Pull request by LetterShapedGlyphs**
Forge recently added a new attribute for swimming speed that is accurate and allows for multiple mods to affect it without incompatibility. Despite increasing the % modifier, it is still slower than previous due to properly handling friction and player input, so some balance testing may be required.

### CODE REVIEW

**Comment by LetterShapedGlyphs** [comment]
As a note: While the new attribute technically applies to lava as well, it doesn't have any of the previous problems which would come up when trying to speed up lava swimming such as: Being really fast even at what should be a low percent, or being unable to leave the lava.

**Comment by TheIllusiveC4** [comment]
Thanks for this, I never really liked the previous way of modifying swim speed. This looks much cleaner.

**Comment by TheIllusiveC4** [comment]
Tested and working as expected. Although I will note that it seems like there isn't an entry in the Forge lang file for this attribute.

**Comment by LetterShapedGlyphs** [comment]
Woops XD I didn't realize that attributes had lang data and no one called me out on it in the Forge PR. I'll submit a new one to add that.

**Pull request merged**
